---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Ensure parent folders of link dotfiles exist.
  file:
    path: "{{ (dotfiles_home ~ '/' ~ item) | dirname }}"
    state: directory
    follow: true
  become: false
  with_items: "{{ dotfiles_files }}"

- name: Link dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: link
    force: true
  become: false
  with_items: "{{ dotfiles_files }}"
